---
- name: Install Apache
  apt: pkg=apache2

- name: Enable cgi for apache
  apache2_module:
    name: cgid
    state: present
  notify: restart apache

- name: Allow symlinks for cgi scripts
  lineinfile:
    path: /etc/apache2/conf-available/serve-cgi-bin.conf
    regexp: '^\s*Options.*\+ExecCGI'
    line: 'Options +ExecCGI -MultiViews'
  notify: restart apache
