---
- name: Install Apache
  apt: name=apache2

- name: Enable cgi for apache
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - ssl
    - cgid
  notify: restart apache

- name: Chown /var/www/html to zverik
  file:
    path: /var/www/html
    owner: zverik
    group: zverik

- name: Add robots.txt
  copy:
    content: |
      User-agent: *
      Disallow: /
    dest: /var/www/html/robots.txt

- name: Allow symlinks for cgi scripts
  lineinfile:
    path: /etc/apache2/conf-available/serve-cgi-bin.conf
    regexp: '^\s*Options.*\+ExecCGI'
    line: 'Options +ExecCGI -MultiViews'
  notify: restart apache
