---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - geerlingguy.ntp
    - apache
    - firewall
    - postgis
    - python3
    - { role: backup, tags: backup }

- hosts: all
  remote_user: zverik
  roles:
    - { role: tile_server, tags: tiles }
    - { role: osm2008, tags: osm2008 }
    - { role: get_veloroad, tags: get_veloroad }
    - { role: a5a4, tags: a5a4 }
    - { role: stats, tags: stats }
    - { role: hitrye, tags: hitrye }
    - { role: hitrye_archive, tags: hitrye_archive }
    - { role: mayak_nav_bot, tags: mayak_nav_bot }
    - { role: mark_spam_bot, tags: mark_spam_bot }
    - { role: teleput, tags: teleput }
    - { role: geoscribble, tags: geoscribble }
