---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - geerlingguy.ntp
    - apache
    - firewall
    - postgis
    - python3
    - backup

- hosts: all
  remote_user: zverik
  roles:
    - tile_server
    - osm2008
    - get_veloroad
    - a5a4
    - stats
    - hitrye
    - schedules
    - mayak_nav_bot
    - mark_spam_bot
    - teleput
    - integratsioon
    - { role: geoscribble, tags: geoscribble }
