---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - role: tersmitten.swapfile
      swapfile_size: 1000M
    - geerlingguy.ntp
    - apache
    - firewall
    - postgis
    - python3

- hosts: all
  remote_user: zverik
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  roles:
    - tile_server
    - osm2008
    - get_veloroad
    - queryat
    - a5a4
    - stats
    - mmwatch
    - hitrye
    - rails_port
    - podcast_lengths
