---
- hosts: all
  gather_facts: no
  become: yes
  remote_user: root
  roles:
    - common

- hosts: all
  become: yes
  remote_user: root
  roles:
    - geerlingguy.ntp
    - apache
    - firewall
    - postgis
    - python3
    - { role: backup, tags: backup }

- hosts: all
  remote_user: zverik
  roles:
    - tile_server
    - osm2008
    - { role: get_veloroad, tags: get_veloroad }
    - a5a4
    - stats
    - { role: hitrye, tags: hitrye }
    - { role: schedules, tags: schedules }
    - { role: mayak_nav_bot, tags: mayak_nav_bot }
    - { role: mark_spam_bot, tags: mark_spam_bot }
    - { role: teleput, tags: teleput }
    - { role: integratsioon, tags: integratsioon }
    - { role: geoscribble, tags: geoscribble }
