---
- name: Check out na_rayone code
  git:
    repo: https://github.com/Zverik/bot_na_rayone.git
    dest: /opt/src/mayak_nav
  notify: restart mayak_nav
  tags: [mayak_nav, mayak_update]

- name: Create virtualenv for na_rayone
  pip:
    requirements: /opt/src/mayak_nav/requirements.txt
    virtualenv: /opt/src/mayak_nav/venv
  tags: mayak_nav

- name: Make log directory
  become: yes
  file:
    path: /var/log/mayak_nav_bot
    state: directory
    owner: zverik
    group: zverik
  tags: mayak_nav

- name: Make config directory
  file:
    path: /opt/src/mayak_nav/config
    state: directory
  tags: mayak_nav

- name: Upload mayak_nav config
  template:
    src: config.yml
    dest: /opt/src/mayak_nav/config/config.yml
  notify: restart mayak_nav
  tags: [mayak_nav, mayak_update]

- name: Upload responses yml
  copy:
    src: responses.yml
    dest: /opt/src/mayak_nav/config/responses.yml
  notify: restart mayak_nav
  tags: [mayak_nav, mayak_update]

- name: Decrypt addr yml
  copy:
    src: addr.yml
    dest: /opt/src/mayak_nav/config/addr.yml
  notify: restart mayak_nav
  tags: [mayak_nav, mayak_update]

- name: Create empty photo directory
  file:
    path: /opt/src/mayak_nav/config/photo
    state: directory
  tags: mayak_nav

- name: Upload tiles
  unarchive:
    src: tiles.tar
    dest: /opt/src/mayak_nav/config
    owner: zverik
    group: zverik
  tags: mayak_nav

- name: Create systemd service
  become: yes
  copy:
    src: mayak_nav_bot.service
    dest: /etc/systemd/system/
  notify: restart mayak_nav
  tags: mayak_nav

- name: Enable mayak systemd module
  become: yes
  systemd:
    name: mayak_nav_bot
    enabled: yes
  tags: mayak_nav

- name: Set up backups
  become: yes
  import_tasks: backup.yml
