---
- name: Checkout podcasts
  git:
    repo: https://github.com/Zverik/podcast_duration.git
    dest: /opt/src/podcast_duration
  notify: touch podcasts

- name: Create virtualenv for podcasts
  pip:
    name: flask
    virtualenv: /opt/src/podcast_duration/venv

- name: Set up mod_wsgi for podcasts
  become: yes
  blockinfile:
    path: /etc/apache2/sites-available/get_veloroad.conf
    marker: '# {mark} podcasts'
    block: |
      WSGIScriptAlias /pdur /opt/src/podcast_duration/podcast_duration_web.wsgi
      <Directory /opt/src/podcast_duration>
          Require all granted
      </Directory>
  notify: reload apache

- name: Initialize log file
  become: yes
  copy:
    content: ""
    dest: /var/log/podcast_duration.log
    force: no
    owner: zverik
    mode: 0644

- name: Permissions for uploading the data file
  file:
    path: /opt/src/podcast_duration
    state: directory
    mode: 0777

- name: Set up crontab for the updated
  cron:
    name: podcast_updater
    job: /opt/src/podcast_duration/poll_update.sh 2>> /var/log/podcast_duration.log
