---
- name: Check out sotm_intro_bot code
  git:
    repo: https://github.com/Zverik/sotm_intro_bot.git
    dest: /opt/src/sotm_intro_bot
  notify: restart sotm_intro_bot

- name: Create virtualenv for sotm_intro_bot
  pip:
    requirements: /opt/src/sotm_intro_bot/requirements.txt
    virtualenv: /opt/src/sotm_intro_bot/venv

- name: Upload sotm_intro_bot config
  template:
    src: config.py
    dest: /opt/src/sotm_intro_bot/config.py
  notify: restart sotm_intro_bot

- name: Create systemd service
  become: yes
  copy:
    src: sotm_intro_bot.service
    dest: /etc/systemd/system/
  notify: restart sotm_intro_bot

- name: Enable sotm_intro_bot systemd module
  become: yes
  systemd:
    name: sotm_intro_bot
    enabled: yes

- name: Set up backups
  become: yes
  import_tasks: backup.yml
