---
- name: Install packages for osm-carto
  become: yes
  apt:
    name:
      - npm
      - nodejs
      - mapnik-utils
      - curl
    state: present

- name: Install carto
  become: yes
  npm: name=carto global=yes

- name: Download osm-carto {{ branch }} style
  git:
    repo: https://github.com/gravitystorm/openstreetmap-carto.git
    version: "{{ branch }}"
    dest: /opt/styles/{{ dir }}
    update: no

- name: Download shapefiles
  command: scripts/get-external-data.py
  args:
    chdir: /opt/styles/{{ dir }}
    creates: /opt/styles/{{ dir }}/data/antarctica-icesheet-polygons-3857/icesheet_polygons.index
  when: branch != 'master'

- name: Download fonts
  command: scripts/get-fonts.sh
  args:
    chdir: /opt/styles/{{ dir }}
    creates: /opt/styles/{{ dir }}/fonts/NotoEmoji-Bold.ttf
  when: branch != 'master'

- name: Find temporary archives
  find:
    path: /opt/styles/{{ dir }}/data
    patterns: '*.zip,*.tgz'
  register: zips

- name: Delete temporary archives
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ zips.files }}"

- name: Symlink shapefile directory to ../osm-carto
  file:
    path: /opt/styles/{{ dir }}/data
    src: /opt/styles/osm-carto/data
    state: link
  when: branch == 'master'

- name: Create xml for osm-carto
  command: carto -q project.mml -f osm.xml
  args:
    chdir: /opt/styles/{{ dir }}
    creates: /opt/styles/{{ dir }}/osm.xml

- name: Replace tables names in osm-carto
  replace:
    path: /opt/styles/{{ dir }}/osm.xml
    regexp: 'planet_osm_'
    replace: 'old_'

- name: Add renderd section for osm-carto
  become: yes
  blockinfile:
    path: /usr/local/etc/renderd.conf
    insertafter: EOF
    marker: '# {mark} osm-carto'
    block: |
      [osm]
      URI=/osm/
      TILEDIR=/var/lib/mod_tile
      XML=/opt/styles/{{ dir }}/osm.xml
      HOST={{ render_host }}
      TILESIZE=512
      SCALE=2
      MINZOOM=4
      MAXZOOM=18
  when: branch != 'master'

- name: Add renderd section for osm-carto-4
  become: yes
  blockinfile:
    path: /usr/local/etc/renderd.conf
    insertafter: EOF
    marker: '# {mark} osm-carto 4'
    block: |
      [old]
      URI=/old/
      TILEDIR=/var/lib/mod_tile
      XML=/opt/styles/{{ dir }}/osm.xml
      HOST={{ render_host }}
      TILESIZE=256
      MINZOOM=4
      MAXZOOM=18
  when: branch == 'master'
