---
gisdb: gis
render_user: osm
render_host: tile.osmz.ru
ntp_timezone: Europe/Moscow
admin_email: ilya@zverev.info

icecast_location: Amsterdam
icecast_admin_email: ilya@zverev.info
icecast_hostname: tile.osmz.ru
icecast_admin_password: "{{ v_icecast_admin_password }}"
icecast_relay_password: "{{ v_icecast_source_password }}"
icecast_source_password: "{{ v_icecast_source_password }}"
