---
gisdb: gis
render_user: osm

icecast_location: Amsterdam
icecast_admin_email: ilya@zverev.info
icecast_admin_user: admin
icecast_admin_password: "{{ v_icecast_admin_password }}"
icecast_source_password: "{{ v_icecast_source_password }}"
icecast_hostname: tile.osmz.ru
icecast_listen_sockets:
  - port: 8000
