---
- name: Upload the home backup script
  copy:
    src: backup_files
    dest: /etc/cron.daily/backup_files
    mode: 0700

- name: Test if we're restoring
  set_fact:
    restoring: "{{ 'restore' in ansible_run_tags }}"

- name: Restore home
  when: restoring
  command:
    argv:
      - "/root/extract_backup"
      - "Tile_"
      - '*'
    chdir: /
