---
- name: Download borg
  get_url:
    url: "https://github.com/borgbackup/borg/releases/download/{{ borg_version }}/borg-linux64"
    dest: /usr/local/bin/borg
    mode: 0755
    checksum: "md5:{{ borg_exec_md5 }}"

- name: Create a private key
  copy:
    content: "{{ borg_key }}"
    dest: /root/.ssh/borg
    mode: 0600

- name: Add rsync.net to authorized keys
  known_hosts:
    host: ch-s012.rsync.net
    key: "{{ rsync_key }}"

- name: Add compacting job once a week
  template:
    src: compact_backups.j2
    dest: /etc/cron.weekly/compact_backups
    mode: 0700

- name: Upload the extraction script
  template:
    src: extract_backup.j2
    dest: /root/extract_backup
    mode: 0700

- name: Set up home backups
  import_tasks: home.yml
