---
- name: Create render user
  user:
    name: "{{ render_user }}"
    createhome: no

- name: Install PostgreSQL and PostGIS
  apt:
    name:
      - "postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
      - python3-psycopg2
    state: present

- name: Create database roles
  become: yes
  become_user: postgres
  postgresql_user: name={{ item }}
  with_items:
    - "{{ render_user }}"
    - zverik
    - www-data
