---
- name: Install fail2ban package
  apt: name=fail2ban state=latest

- name: Copy fail2ban config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Start fail2ban service
  systemd: name=fail2ban state=started enabled=yes
