---
- name: Check out teleput code
  git:
    repo: https://github.com/Zverik/teleput-server.git
    dest: /opt/src/teleput
  notify: restart teleput
  tags: update-teleput

- name: Create virtualenv for teleput
  pip:
    requirements: /opt/src/teleput/requirements.txt
    virtualenv: /opt/src/teleput/venv
  tags: update-teleput

- name: Upload teleput config
  template:
    src: config_local.j2
    dest: /opt/src/teleput/config_local.py
  notify: restart teleput
  tags: update-teleput

- name: Create teleput systemd service
  become: yes
  copy:
    src: teleput.service
    dest: /etc/systemd/system/
  notify: restart teleput

- name: Enable teleput systemd module
  become: yes
  systemd:
    name: teleput
    enabled: yes

- name: Ensure http_proxy is enabled
  become: yes
  apache2_module:
    name: proxy_http
    state: present

- name: Check that certificates exist
  stat:
    path: /etc/letsencrypt/certs/fullchain_teleput.textual.ru.crt
  register: cert_file

- name: Upload teleput apache config
  when: cert_file.stat.exists
  become: yes
  template:
    src: teleput.conf
    dest: /etc/apache2/sites-available/teleput.conf
  notify: reload apache

- name: Create teleput document root
  become: yes
  file:
    path: /var/www/teleput
    state: directory
    owner: zverik

- name: Enable teleput config if not yet
  become: yes
  file:
    src: /etc/apache2/sites-available/teleput.conf
    path: /etc/apache2/sites-enabled/teleput.conf
    state: link
  notify: reload apache

- name: Set up backups
  become: yes
  import_tasks: backup.yml
