---
- name: Ensure py2 wsgi is not installed
  apt: pkg=libapache2-mod-wsgi state=absent

- name: Install packages
  apt: pkg={{ item }}
  with_items:
    - python3
    - python3-pip
    - python3-mapnik
    - python3-psycopg2
    - libapache2-mod-wsgi-py3

- name: Install virtualenv for python3
  pip:
    name: virtualenv
    executable: pip3
