---
- name: Ensure py2 wsgi is not installed
  apt: name=libapache2-mod-wsgi state=absent

- name: Install packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-mapnik
      - python3-psycopg2
      - libapache2-mod-wsgi-py3
    state: present

- name: Install virtualenv for python3
  pip:
    name: virtualenv
    executable: pip3

- name: Install repo for python 3.9 and higher
  become: yes
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Install python 3.9
  become: yes
  apt:
    pkg:
      - python3.9
      - python3.9-venv
      - python3.9-dev
    state: present
    update_cache: yes
