---
- name: Ensure py2 wsgi is not installed
  apt: name=libapache2-mod-wsgi state=absent

- name: Install packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-mapnik
      - python3-psycopg2
      - libapache2-mod-wsgi-py3
    state: present

- name: Install virtualenv for python3
  pip:
    name: virtualenv
    executable: pip3
