---
- name: Check out mark_spam code
  git:
    repo: https://github.com/Zverik/mark_spam_bot.git
    dest: /opt/src/mark_spam_bot
  notify: restart mark_spam

- name: Create virtualenv for mark_spam
  pip:
    requirements: /opt/src/mark_spam_bot/requirements.txt
    virtualenv: /opt/src/mark_spam_bot/venv

- name: Upload mark_spam config
  template:
    src: config.j2
    dest: /opt/src/mark_spam_bot/config.py
  notify: restart mark_spam

- name: Create systemd service
  become: yes
  copy:
    src: mark_spam_bot.service
    dest: /etc/systemd/system/
  notify: restart mark_spam

- name: Enable mark_spam systemd module
  become: yes
  systemd:
    name: mark_spam_bot
    enabled: yes

- name: Set up backups
  become: yes
  import_tasks: backup.yml
