---
- name: reload apache
  systemd: name=apache2 state=reloaded

- name: restart apache
  systemd: name=apache2 state=restarted

- name: restart renderd
  systemd: name=renderd state=restarted

- name: restart postgresql
  systemd: name=postgresql state=restarted
