---
- name: reload apache
  become: yes
  systemd: name=apache2 state=reloaded

- name: restart apache
  become: yes
  systemd: name=apache2 state=restarted

- name: restart renderd
  become: yes
  systemd: name=renderd state=restarted

- name: restart postgresql
  become: yes
  systemd: name=postgresql state=restarted
