---
- name: Create geoscribble database
  become: yes
  become_user: postgres
  postgresql_db:
    name: geoscribble
    encoding: UTF-8
    owner: zverik

- name: Add postgis extension
  become: yes
  become_user: postgres
  postgresql_ext:
    db: geoscribble
    name: postgis

- name: Allow local no password access to the database
  become: yes
  become_user: postgres
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    insertafter: '# TYPE\s*DATABASE'
    regexp: '^local geoscribble'
    line: local geoscribble zverik trust
  notify: restart postgresql

- name: Check out geoscribble code
  git:
    repo: https://github.com/Zverik/geoscribble.git
    dest: /opt/src/geoscribble
  notify: restart geoscribble

- name: Create virtualenv for geoscribble
  pip:
    requirements: /opt/src/geoscribble/requirements.txt
    virtualenv: /opt/src/geoscribble/.venv

- name: Initialize log
  become: yes
  file:
    path: /var/log/geoscribble.log
    owner: zverik
    state: touch

- name: Create systemd service
  become: yes
  copy:
    src: geoscribble.service
    dest: /etc/systemd/system/
  notify: restart geoscribble

- name: Enable geoscribble systemd module
  become: yes
  systemd:
    name: geoscribble
    enabled: yes

- name: Ensure http_proxy is enabled
  become: yes
  apache2_module:
    name: proxy_http
    state: present

- name: Check that certificates exist
  stat:
    path: /etc/letsencrypt/certs/fullchain_geoscribble.osmz.ru.crt
  register: gs_cert_file

- name: Upload geoscribble apache config
  become: yes
  template:
    src: geoscribble.conf
    dest: /etc/apache2/sites-available/geoscribble.conf
  notify: reload apache

- name: Create geoscribble document root
  become: yes
  file:
    path: /var/www/geoscribble
    state: directory
    owner: zverik

- name: Enable geoscribble config if not yet
  become: yes
  file:
    src: /etc/apache2/sites-available/geoscribble.conf
    path: /etc/apache2/sites-enabled/geoscribble.conf
    state: link
  notify: reload apache

- name: Install geoscribble backup script
  become: yes
  template:
    src: backup_geoscribble.j2
    dest: /etc/cron.daily/backup_geoscribble
    mode: 0700
