---
- name: Check that certificates exist
  stat:
    path: /etc/letsencrypt/certs/fullchain_hitrye.ru.crt
  register: cert_file

- name: Upload apache config
  template:
    src: hitrye.conf
    dest: /etc/apache2/sites-available
  notify: reload apache

- name: Create apache log dir
  file:
    path: /var/log/apache2/hitrye
    state: directory

- name: Upload logrotate config
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/apache2-hitrye

- name: Symlink apache config
  file:
    src: /etc/apache2/sites-available/hitrye.conf
    dest: /etc/apache2/sites-enabled/hitrye.conf
    state: link
  notify: reload apache
