---
- name: Download borg
  get_url:
    url: https://github.com/borgbackup/borg/releases/download/1.1.14/borg-linux64
    dest: /usr/local/bin/borg
    mode: 0755
    checksum: md5:e3758a85d7ceaff0a19e8f2163ddfbc2

- name: Create a private key
  copy:
    content: "{{ borg_key }}"
    dest: /root/.ssh/borg
    mode: 0600

- name: Add rsync.net to authorized keys
  known_hosts:
    host: ch-s012.rsync.net
    key: 'ch-s012.rsync.net,82.197.184.220 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO5lfML3qjBiDXi4yh3xPoXPHqIOeLNp66P3Unrl+8g3'

- name: Install backup script
  template:
    src: backup_hitrye.j2
    dest: /etc/cron.daily/backup_hitrye
    mode: 0700
