---
- name: Install php packages
  apt:
    name:
      - php
      - php-gd
      - php-imagick
      - php-json
      - php-mcrypt
      - php-pgsql
      - php-xml
      - php-zip
      - libapache2-mod-php
      - imagemagick
      - unzip
    state: present
