---
- name: Check that phpbb is installed
  stat:
    path: "{{ hitrye_path }}/index.php"
  register: phpbbf

- name: Check that language is installed
  stat:
    path: "{{ hitrye_path }}/language/ru/common.php"
  register: phpbbl

- name: Read the installed version
  when: phpbbf.stat.exists
  slurp:
    src: /opt/phpbb.version
  register: version64

- name: Parse the installed version
  when: version64.content is defined
  set_fact:
    phpbb_server_version: "{{ version64.content | b64decode | trim }}"

- name: Alternatively, set installed version to a dummy
  when: phpbb_server_version is not defined
  set_fact:
    phpbb_server_version: old

- name: Download phpbb
  when: phpbb_server_version != phpbb.version
  get_url:
    url: https://www.phpbb.com/files/release/phpBB-{{ phpbb.version }}.zip
    dest: /var/tmp/phpbb.zip
    checksum: "{{ phpbb.checksum }}"

- name: Download Russian language pack
  when: phpbb_server_version != phpbb.version
  get_url:
    url: "{{ phpbb_lang.url }}"
    dest: /var/tmp/phpbb-ru.zip
    checksum: "{{ phpbb_lang.checksum }}"

- name: Create target dir
  become: yes
  file:
    path: "{{ hitrye_path }}"
    owner: zverik
    group: zverik
    state: directory

- name: Unpack phpbb
  when: phpbb_server_version != phpbb.version
  unarchive:
    remote_src: yes
    src: /var/tmp/phpbb.zip
    dest: /var/tmp

- name: Unpack langpack
  when: phpbb_server_version != phpbb.version
  unarchive:
    remote_src: yes
    src: /var/tmp/phpbb-ru.zip
    dest: /var/tmp

- name: Move phpbb to /var/www
  when: not phpbbf.stat.exists
  shell: "mv /var/tmp/phpBB3/* {{ hitrye_path }}/"
  args:
    creates: "{{ hitrye_path }}/index.php"

- name: Find phpbb files to update
  when:
    - phpbbf.stat.exists
    - phpbb_server_version != phpbb.version
  find:
    path: /var/tmp/phpBB3
    file_type: any
    recurse: no
    excludes:
      - config.php
      - images
      - files
  register: hitrye_files

- name: Update phpbb files
  when: hitrye_files.files is defined
  shell: cp -r "{{ item.path }}" {{ hitrye_path }}/
  with_items: "{{ hitrye_files.files }}"

- name: Copy language to phpbb installation
  when: phpbb_server_version != phpbb.version
  shell: "cp -r /var/tmp/{{ phpbb_lang.dir }}/* {{ hitrye_path }}/"

- name: Delete phpbb.zip
  file:
    path: /var/tmp/{{ item }}
    state: absent
  with_items:
    - phpbb.zip
    - phpbb-ru.zip
    - phpBB3
    - "{{ phpbb_lang.dir }}"

- name: Upload config.php
  copy:
    src: config.php
    dest: "{{ hitrye_path }}/config.php"

- name: Chmod user directories
  file:
    path: "{{ hitrye_path }}/{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - store
    - cache
    - files 
    - images/avatars/upload

- name: Upgrade the database
  when:
    - phpbbf.stat.exists
    - phpbb_server_version != phpbb.version
  shell: php bin/phpbbcli.php --safe-mode db:migrate
  args:
    chdir: "{{ hitrye_path }}"

- name: Delete install directory
  file:
    path: "{{ hitrye_path }}/install"
    state: absent

- name: Clear cache
  when:
    - phpbbf.stat.exists
    - phpbb_server_version != phpbb.version
  become: yes
  file:
    path: "{{ hitrye_path }}/cache/production"
    state: absent

- name: Copy old smilies
  copy:
    src: "{{ item }}"
    dest: "{{ hitrye_path }}/images/smilies/{{ item }}"
  with_items:
    - icon_e_biggrin.gif
    - icon_e_sad.gif
    - icon_e_smile.gif
    - icon_e_wink.gif

- name: Write installed version
  become: yes
  copy:
    content: "{{ phpbb.version }}"
    dest: /opt/phpbb.version
    force: yes
