---
- name: Check that recent topics is installed
  stat:
    path: /var/www/hitrye/ext/paybas/recenttopics/ext.php
  register: rt

- name: Download Recent Topics extension
  when: not rt.stat.exists
  get_url:
    url: https://www.phpbb.com/customise/db/download/180056
    dest: /var/tmp/recent.zip
    checksum: md5:21d1bf2cee0e0085a55b032d0f1526cd

- name: Unpack recent topics
  when: not rt.stat.exists
  unarchive:
    remote_src: yes
    src: /var/tmp/recent.zip
    dest: /var/tmp

- name: Move recent topics to phpbb
  shell: mv /var/tmp/paybas /var/www/hitrye/ext/
  args:
    creates: /var/www/hitrye/ext/paybas/recenttopics/ext.php

- name: Cleanup recent topics
  file:
    path: /var/tmp/{{ item }}
    state: absent
  with_items:
    - recent.zip
    - paybas
