---
- name: Install all required packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - ruby2.3
    - libruby2.3
    - ruby2.3-dev
    - imagemagick
    - libmagickwand-dev
    - libxml2-dev
    - libxslt1-dev
    - libapache2-mod-passenger
    - postgresql-server-dev-all

#- name: Install bundler - does not work!
#  become: yes
#  gem:
#    name: bundler
#    state: present
#    user_install: no

- name: Check that bundler is not installed
  command: which bundle
  register: bundle
  changed_when: False
  ignore_errors: yes

- name: Install bundler
  when: bundle.failed
  become: yes
  command: gem2.3 install bundler

- name: Clone osm-website
  git:
    repo: https://github.com/zverik/openstreetmap-website.git
    version: mapsme
    dest: /opt/src/openstreetmap-website

- name: Install gems
  bundler:
    chdir: /opt/src/openstreetmap-website
    state: present
    deployment_mode: yes

- name: Copy application config
  template:
    src: application.yml.j2
    dest: /opt/src/openstreetmap-website/config/application.yml

- name: Copy database config
  copy:
    src: database.yml
    dest: /opt/src/openstreetmap-website/config/database.yml

- name: Create db
  become: yes
  become_user: postgres
  import_tasks: db.yml

- name: Create tables and functions
  import_tasks: db_post.yml

- name: Precompile assets
  shell: RAILS_ENV=production bundle exec rake assets:precompile
  args:
    chdir: /opt/src/openstreetmap-website
    creates: /opt/src/openstreetmap-website/public/assets/images
  notify: restart apache

- name: Publish website
  become: yes
  import_tasks: passenger.yml
