---
- name: Install icecast
  apt: name=icecast2

- name: Upload configuration file
  template: 
    src: icecast.xml.j2 
    dest: /etc/icecast2/icecast.xml
    owner: icecast2
    group: icecast
    mode: 0644
  notify: 
    - reload icecast

- name: Enable Icecast in the config
  lineinfile:
    path: /etc/default/icecast2
    regexp: '^\s*ENABLE'
    line: 'ENABLE=true'
    state: present

- name: Enable Icecast service
  systemd: name=icecast2 enabled=yes state=started

- name: Open port 8000
  ufw:
    rule: allow
    port: 8000
  notify: restart ufw
