---
- name: Copy bundled scripts
  copy:
    src: "{{ item }}"
    dest: /opt/src/{{ item }}
    mode: 0755
  with_items:
    - expandjson.py
    - findbuildings.py

- name: Link to cgi scripts
  become: yes
  file:
    path: /usr/lib/cgi-bin/{{ item.dest }}.py
    src: /opt/src/{{ item.src }}.py
    state: link
  with_items:
    - { dest: expandjson, src: expandjson }
    - { dest: findbuildings, src: findbuildings }
