---
- name: Install packages
  become: yes
  apt: pkg={{ item }}
  with_items:
    - libapache2-mod-wsgi

- name: Enable cgi for apache
  become: yes
  command: a2enmod cgid
  register: output
  changed_when: "'Enabling conf cgid' in output.stdout"
  notify: restart apache

- name: Checkout apps
  git:
    repo: https://github.com/Zverik/{{ item }}.git
    dest: /opt/src/{{ item }}
  with_items:
    - a5a4
    - nik4cgi
    - Nik4

- name: Copy bundled scripts
  copy:
    src: "{{ item }}"
    dest: /opt/src/{{ item }}
    mode: 0755
  with_items:
    - expandjson.py
    - findbuildings.py

- name: Allow symlinks for cgi scripts
  become: yes
  lineinfile:
    path: /etc/apache2/conf-available/serve-cgi-bin.conf
    regexp: '^\s*Options.*\+ExecCGI'
    line: 'Options +ExecCGI -MultiViews'

- name: Link to cgi scripts
  become: yes
  file:
    path: /usr/lib/cgi-bin/{{ item.dest }}.py
    src: /opt/src/{{ item.src }}.py
    state: link
  with_items:
    - { dest: expandjson, src: expandjson }
    - { dest: findbuildings, src: findbuildings }
    - { dest: nik4cgi, src: nik4cgi/cgi-bin/nik4cgi }
    - { dest: pdfjamcgi, src: a5a4/cgi/pdfjamcgi }

- name: Symlink get-veloroad html
  become: yes
  file:
    path: /var/www/html/get
    src: /opt/src/nik4cgi/www
    state: link

- name: Grant www-data user access to postgresql/osm
  become: yes
  lineinfile:
    path: /etc/postgresql/9.5/main/pg_hba.conf
    insertafter: '# TYPE\s*DATABASE'
    regexp: '^local gis'
    line: local gis osm trust
  notify: restart postgresql

# TODO: create veloroad-r.xml, veloroad-en.xml and osm-r.xml
