---
- name: Ensure py2 wsgi is not installed
  become: yes
  apt: pkg=libapache2-mod-wsgi state=absent

- name: Install packages
  become: yes
  apt: pkg={{ item }}
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-mapnik
    - python3-psycopg2
    - libapache2-mod-wsgi-py3

- name: Grant www-data user access to postgresql/osm
  become: yes
  lineinfile:
    path: /etc/postgresql/9.5/main/pg_hba.conf
    insertafter: '# TYPE\s*DATABASE'
    regexp: '^local gis'
    line: local gis osm trust
  notify: restart postgresql

- name: Install CGI scripts
  import_tasks: cgi.yml

- name: Install get_veloroad
  import_tasks: nik4.yml

- name: Install queryat
  import_tasks: queryat.yml

- name: Install a5a4
  import_tasks: a5a4.yml
