---
- name: Create gis database
  import_tasks: create_gis_db.yml

- name: Install tile packages
  become: yes
  apt: pkg={{ item }}
  with_items:
    - osm2pgsql
    - osmosis
    - libmapnik3.0

- name: Install mod_tile
  import_tasks: mod_tile.yml

- name: Install osm-carto v3 style
  import_tasks: osm_carto.yml
  vars:
    branch: v3.x
    dir: osm-carto

- name: Install veloroad style
  import_tasks: veloroad.yml

- name: Install sample pbf file
  import_tasks: sample_pbf.yml

- name: Set up replication
  import_tasks: replication.yml

- name: Start renderd
  become: yes
  systemd: name=renderd state=started
