---
- name: Install packages for mod_tile
  become: yes
  apt:
    name:
      - apache2-dev
      - git
      - autoconf
      - automake
      - m4
      - libtool
      - libmapnik-dev
      - libapache2-mod-tile
    state: present

- name: Create mod_tile dirs
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ render_user }}"
    state: directory
  with_items:
    - /var/lib/mod_tile
    - /var/run/renderd

- name: Copy empty renderd.conf
  become: yes
  copy:
    src: renderd.conf
    dest: /etc/renderd.conf
    force: no

- name: Copy apache module config
  become: yes
  copy:
    src: mod_tile.conf
    dest: /etc/apache2/conf-available/mod_tile.conf

- name: Enable mod_tile apache module
  become: yes
  command: a2enconf mod_tile
  register: output
  changed_when: "'Enabling conf mod_tile' in output.stdout"
  notify: restart apache

- name: Add renderd section to apache
  become: yes
  copy:
    src: site.conf
    dest: /etc/apache2/sites-available/renderd.conf
  notify: restart apache

- name: Enable the renderd site
  become: yes
  command: a2ensite renderd
  notify: restart apache

- name: Disable the default site
  become: yes
  command: a2dissite 000-default
  notify: restart apache

- name: Edit renderd service to replace the user account
  become: yes
  lineinfile:
    path: /lib/systemd/system/renderd.service
    regexp: '^User='
    line: User={{ render_user }}

- name: Enable renderd systemd module
  become: yes
  systemd: name=renderd enabled=yes
