---
- name: Install packages for osm2pgsql
  become_user: root
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - automake
    - g++
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libbz2-dev
    - libgeos++-dev
    - libgeos-dev
    - liblua5.2-dev
    - libpq-dev
    - libproj-dev
    - libprotobuf-c0-dev
    - libtool
    - libxml2-dev
    - lua5.2
    - make
    - protobuf-c-compiler

- name: Checkout osm2pgsql source
  git: repo=https://github.com/openstreetmap/osm2pgsql.git dest=/opt/src/osm2pgsql update=no

- name: Compile osm2pgsql
  shell: chdir=/opt/src/osm2pgsql ./autogen.sh && ./configure && ./make
  register: osm2pgsql_result

- name: Install osm2pgsql
  become_user: root
  command: make install chdir=/opt/src/osm2pgsql
  when: osm2pgsql_result|success
